name: Test

on: push

env:
  CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE_ID }}
  GIT_BRANCH: ${{ github.ref }}
  GIT_COMMIT_SHA: ${{ github.sha }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - run: go get -v github.com/axw/gocov/gocov
      - run: go get -v github.com/AlekSi/gocov-xml

      - name: download cc test reporter
        run: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter

      - run: ./cc-test-reporter before-build
      - run: gocov test ./... | gocov-xml > coverage.xml
      - run: ./cc-test-reporter format-coverage -t cobertura coverage.xml
      - run: ./cc-test-reporter after-build -t gocov
