name: Test

on: push

env:
  CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE_ID }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - run: go get -v go get github.com/axw/gocov/gocov
      - run: go get -v go get github.com/codeclimate/test-reporter

      - run: GIT_BRANCH=$GITHUB_REF GIT_COMMIT_SHA=$GITHUB_SHA test-reporter before-build

      - run: gocov test ./...

      - run: GIT_BRANCH=$GITHUB_REF GIT_COMMIT_SHA=$GITHUB_SHA test-reporter after-build -t gocov
